### ISSUE TITLE
Request support for new massacre system

### ISSUE THREAD

**Issue by svange** [kylewill0725/EDPirateMissionTracker#10]
Hello, love the tool. I wonder how modular it is! Is it possible to replace the minor factions easily?

I have a system, HIP 108701, that is a viable AFK Imperial grind.

The HIP 108701 tab in the following spreadsheet outlines the minor factions in play here.

https://docs.google.com/spreadsheets/d/1SBNSOunQFqlCuk3b-5OHF7B1KUBjycbchCDD7QQbfzU/edit?usp=sharing

These are the minor factions and systems they're in.

- HIP 108701 Autocracy 
  - location: HIP 108729
  
- HIP 108729 Empire League 
  - location: HIP 108729
  
- HIP 108729 Central Corp. 
  - location: HIP 108729
  
- HIP 108729 Free 
  - location: HIP 108729
  
- HIP 108729 Industry 
  - location: HIP 108729
  
- Chanarsi Justice Party 
  - location: HIP 108729
  
- HIP 108729 Crimson Raiders 
  - location: HIP 108729
  
- Social Goplang Democrats 
  - location: Goplang
  
- The Kuun-Lan 
  - location: Goplang
  
- Goplang Citizens of Tradition 
  - location: Goplang
  
- Goplang Jet Interstellar 
  - location: Goplang
  
- Goplang Purple Syndicate 
  - location: Goplang
  
- Co-op of Yaguvit 
  - location: HIP 109787 / Goplang
  
- HIP 108971 Guardians 
  - location: HIP 109787
  
- HIP 109787 Nobles 
  - location: HIP 109787
  
- HIP 109787 State Industry 
  - location: HIP 109787
  
- HIP 109787 United & Co 
  - location: HIP 109787
  
- HIP 109787 Collective 
  - location: HIP 109787 / Goplang
  
- HIP 109787 Silver Brothers 
  - location: HIP 109787
  
- HIP 107994 Worker's Party 
  - location: Syntheng
  
- Syntheng Gold Natural PLC 
  - location: Syntheng
  
- Syntheng Universal Corporation 
  - location: Syntheng
  
- Revolutionary Syntheng Values Party 
  - location: Syntheng
  
- Syntheng Imperial Society 
  - location: Syntheng
  
- Syntheng Silver Ring 
  - location: Syntheng

**Comment by kylewill0725** [comment]
Sorry for the reply delay. Currently on haitus do to irl things.

**Comment by svange** [comment]
Nevermind, this thing already works in other pirate system. I assumed Qi Yomissi systems were hardcoded in, but then I just tried it elsewhere and it continues to be awesome. Thanks anyway, please disregard.

**Comment by svange** [comment]
Not an issue, my mistake. Thanks for the tool.
