### ISSUE TITLE
Security issues when downloading

### ISSUE THREAD

**Issue by jmunoz2141** [kylewill0725/EDPirateMissionTracker#11]
Receiving a security message that I am unable to bypass when attempting to download.  Downloading as the admin does not work either.  Currently running Win10.
![Application Install-Security Warning](https://user-images.githubusercontent.com/84143412/118151374-68eb1500-b3c8-11eb-9888-2fc00a1e2352.png)

**Comment by kylewill0725** [comment]
It looks to be an issue with your ClickOnce trust permissions. Here is a link with a solution that resets them back to default: https://superuser.com/a/1488786 . Let me know if this resolves it.

**Comment by jmunoz2141** [comment]
Worked like a charm, thanks!
