### ISSUE TITLE
MainWindow gone blank after re-installation of game

### ISSUE THREAD

**Issue by CALADARI** [kylewill0725/EDPirateMissionTracker#13]
I suffer very low FPS when playing ED:Odessy on my HDD, so i re-installed the game to my SSD.Then I start up Horizon cuz I had some mission to hand in beofre finally migrate to Odessy(the horizon mission are not inherited to odessy).And the tracker just stoped working as picture below, while I have 19 mission active:
![image](https://user-images.githubusercontent.com/45614593/118986126-a5fb6c80-b9b1-11eb-8ee6-5d2e55f6d08f.png)
The journal file are all intact and not moved or modified, the tracker works fine just before I re-install my game (after the odessy release). It just malfunctioned after re-installation.

**Comment by kylewill0725** [comment]
This is probably hitting one of the many edge cases I've found. The current code isn't testable so I'm currently working on a total rewrite. This is going quite slow though as I lack time. To restore functionality:  

1) Finish or abandon current missions
1) Close the game
1) Right click the Windows start button
1) Click "Run"
1) Copy  
`"%userprofile%\Saved Games\Frontier Developments\Elite Dangerous"`  
and paste it in the text box
1) Click "OK"
1) Create a new folder called "Old Journals"
1) Move every file that starts with "Journal" into the "Old Journals" folder
    - (You may want these journals in the future for things like EDDiscovery or EDSM)
1) Restart the game  
  
It should work now.

**Comment by CALADARI** [comment]
@kylewill0725  Its working... Its only not reading THE batch of mission. 
I hand in the batch of mission, migrate to odessy, pick up new batch, function resumed.
 It seems switching between odessy and horizon confuzed the journal file somehow.
My incident should just be conisiderd as a rare sample, no need to fix. But do recommand a 'sync now' of 'manual update' button being add to the tracker.

**Comment by kylewill0725** [comment]
Can you email (kylewill0725@outlook.com) a zip file of the new files found at step 8? Don't include the files from Old Journals. This may be something new with Odyssey which I don't have. If the journal files were moved after the missions were wiped, this will probably happen to anyone in Odyssey.

**Comment by CALADARI** [comment]
okay, I'll include the last file marked as "gameversion":"Fleet Carriers Update - Patch 11", "build":"r254828/r0 " } which is my last log into horizion.
others will be "Odyssey":true, "gameversion":"4.0.0.101", "build":"r268562/r0 " }

Ugh. and just mention , I did not do the steps, just pick up new mission and its working again.
So I do not think its a big thing... just hand in THE batch of mission with out aid of tool ... noting big..

Update : 
The FD is really frequently messing up mission system.Now they just cancled all the mission after a hotfix , so now the tracker shows i have 40 mission lol.
Regarding this, you might want to introduce a sync function or let player manually override mission list... FD's fault tho.
UpUpdate:
solve after restart tracker, it now show mission correctly :|

**Comment by CALADARI** [comment]
Yeah confirmed moving between odessy and horizion will confuse tracker.
The FD just fucked odessy's mission again, I lost another 200M masscure mission. 
So i back to horizon, and find my horizon sitll active while tracker main window blanked.I will try pick up new batch see it the function resums.
